// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV8ux-iMcDj54UR_gxEqv05eUzTa9I1Bo',
    appId: '1:236544433373:web:3e88148691286e675b0f34',
    messagingSenderId: '236544433373',
    projectId: 'race-tracker-118ab',
    authDomain: 'race-tracker-118ab.firebaseapp.com',
    databaseURL:
        'https://race-tracker-118ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'race-tracker-118ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUANbt3LCghMcaCkFYKypqiAwjBKxTp1Y',
    appId: '1:236544433373:android:73985249f473559b5b0f34',
    messagingSenderId: '236544433373',
    projectId: 'race-tracker-118ab',
    databaseURL:
        'https://race-tracker-118ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'race-tracker-118ab.firebasestorage.app',
  );
}
